### ISSUE TITLE
openssh_server resource does not start ssh service on Ubuntu 14.04

### ISSUE THREAD

**Issue by CpuID** [chr4-cookbooks/sshd#10]
openssh_server should start ssh service (using Upstart) on Ubuntu 14.04, but it doesn't at the moment. Tested on Chef 12.1.1 and 12.2.1.

Can login to the machine and start the service fine manually using service ssh start.

Bug in either this cookbook or Chef itself? I see a heap of GH issues on the Chef side relating to Upstart selections etc, and I see the hack in definitions/openssh_server.rb to set the Upstart provider for >13.10. Either way somethings busted :)

Happy to help investigate here if you point me in the right direction.

**Comment by chr4** [comment]
Sorry for the late reply, I must have accidently removed notifications for this repository :(

Can you check whether this problem persists? If so, please reopen the issue.
