### ISSUE TITLE
check_sshd_config block fails on RHEL 5.11 and related EL variants

### ISSUE THREAD

**Issue by sharathdoge** [chr4-cookbooks/sshd#11]
The 'check_sshd_config' block under definitions/openssh_server.rb fails on RHEL 5.11 with the following error.

---- Begin output of sshd -t -f /etc/ssh/sshd_config ----
STDOUT: 
STDERR: sshd re-exec requires execution with an absolute path
---- End output of sshd -t -f /etc/ssh/sshd_config ----
Ran sshd -t -f /etc/ssh/sshd_config returned 255

Modifying the block to use the full path of the sshd binary fixed the issue

  execute 'check_sshd_config' do
    command "/usr/sbin/sshd -t -f #{filename}"
    action :nothing
  end

**Comment by somedamnthing** [comment]
Also seeing this in CentOS 5.11. Of note: re-converge after this failure will work, as the file exists, written during the previous failed converge. If there are issues with the config file, they won't have been checked, but they will be live.

**Comment by gopearls42** [comment]
re-converging wasn't really an option for me -- the Chef run needs to work first time out :(

My work-around was to place a file (using the `file` resource) in /usr/local/sbin, which was before `/usr/sbin` in my `PATH`, that simply calls `/usr/sbin/sshd $*`
