### ISSUE TITLE
Cloned resource warning for 'node['sshd']['service_name']

### ISSUE THREAD

**Issue by somedamnthing** [chr4-cookbooks/sshd#12]
> ```
>   [2016-06-17T17:32:58+00:00] WARN: Cloning resource attributes for service[sshd] from prior resource (CHEF-3694)
>   [2016-06-17T17:32:58+00:00] WARN: Previous service[sshd]: /tmp/kitchen/cache/cookbooks/sshd/recipes/install.rb:29:in `from_file'
>   [2016-06-17T17:32:58+00:00] WARN: Current  service[sshd]: /tmp/kitchen/cache/cookbooks/sshd/definitions/openssh_server.rb:43:in `block in from_file'
> ```

Could probably merge the 'provider' line from install.rb into openssh_server.rb with no issues.

**Comment by Spreadcat** [comment]
Same here. I'd love to contriubute to this, but I am doing chef ~ 3 weeks. Unsure if i can address this problem.

**Comment by chr4** [comment]
Thanks for the report!
Sorry for the late reply, I must have accidently removed notifications for this repository :(

@somedamnthing what do you mean with "merge the provider line"?
I'm considering just removing the `service` statement from the install recipe. I suppose this is not required. Objections?

**Comment by chr4** [comment]
This should be fixed in v1.3.0.
