### ISSUE TITLE
Attribute ordering causes config error when specifying both Port and ListenAddress

### ISSUE THREAD

**Issue by jbillo** [chr4-cookbooks/sshd#8]
When trying to set both the `Port` and `ListenAddress` attributes on Ubuntu 14.04 in combination with this cookbook (`sshd` is version `OpenSSH_6.6.1p1 Ubuntu-2ubuntu2, OpenSSL 1.0.1f 6 Jan 2014`), I get the following error when testing the resulting configuration with `sshd -t`:

```
/etc/ssh/sshd_config line 15: ports must be specified before ListenAddress.
```

Looks like strict alphabetical order as represented in `generate_sshd_config` by `config.sort` doesn't really work for the combination of these two sshd directives.

I've worked around the problem for now by keeping Port as a node attribute, and setting `node['sshd']['sshd_config']['ListenAddress']` to a Hash, where the keys of the hash are IPs or IP/port combinations, and the respective values are empty strings. 

Not sure what the best solution is here - whether it is a special case to have `Port` appear first in the configuration or whether it is worthwhile to have a more in-depth attribute precedence mechanism. If this sufficiently annoys me (since it comes up on nodes with multiple network interfaces/aliases, where I need to specifically bind `sshd` to only listen to certain IP addresses) I'll submit a pull request, but I'd be interested to hear if there are any other ideas.

Thanks!

**Comment by evaryont** [comment]
I'm running into this as well. Any chance you could open a PR?
